name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: "${{ matrix.variants.os }}/${{ matrix.variants.arch }}/${{ matrix.variants.config }}"
    env:
      CMAKE_FLAGS: ''
      NB_CPU: 1
      VERBOSE: 1

    strategy:
      fail-fast: false
      matrix:
        variants:
          - {os: windows-2022,   arch: x64,      config: RelWithDebInfo}
          - {os: windows-2022,   arch: x64,      config: Debug}
          - {os: windows-2022,   arch: win32,    config: RelWithDebInfo}
          - {os: windows-2022,   arch: win32,    config: Debug}

    runs-on: ${{ matrix.variants.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment variables (Windows)
      if: startsWith(matrix.variants.os, 'windows-')
      shell: powershell
      run: |
        echo "NB_CPU=$env:NUMBER_OF_PROCESSORS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Import-Module .\.github\Invoke-VisualStudio.ps1
        Invoke-VisualStudio2022${{ matrix.variants.arch }}

    - name: Initialize cmake
      if: startsWith(matrix.variants.os, 'windows-')
      run: |
        cmake -S . -B ./build -A ${{ matrix.variants.arch }} ${{ env.CMAKE_FLAGS }}

    - name: Initialize cmake (Linux)
      if: startsWith(matrix.variants.os, 'ubuntu-')
      run: |
        cmake -S . -B ./build ${{ env.CMAKE_FLAGS }} -DPWN_BUILD_CRYPTO=${{ matrix.variants.crypto }}

    - name: Build library
      run: |
        cmake --build ./build --parallel ${{ env.NB_CPU }} --config ${{ matrix.variants.config }}

    - name: Install library
      run: |
        cmake --install ./build --config ${{ matrix.variants.config }} --prefix ./artifact --verbose

    - name: Publish artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.variants.crypto == 'ON' }}
      with:
        name: build_${{ matrix.variants.arch }}_${{ matrix.variants.os }}_${{ matrix.variants.config }}_${{ github.sha }}_${{ matrix.variants.build }}
        path: artifact/
